apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: fortune-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort
status:
  loadBalancer: {}