#Build file for dev CI pipeline
name: Simple fortune pipeline
on:
  push:
    branches:
      - "dev/**"
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GET_COMMIT: ${{ github.sha }}
jobs:

  Docker:
    runs-on: ubuntu-latest
    needs: [Build, Test]
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Build and push
      uses: actions/build-push-action@v3
      with:
        push: true
        tags: user/app:latest


  Test: